apiVersion: v1
kind: Service
metadata:
  name: sre-platform
  namespace: sre-platform
spec:
  type: LoadBalancer
  selector:
    app: sre-platform
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
